### ISSUE TITLE
Ability to copy all timezones after scrolling the Time Scroller

### ISSUE THREAD

**Issue by duarteocarmo** [n0shake/clocker#108]
- If you do this currently, all time zones get copied in the current time, not the time I scrolled to.. 

Thanks for the awesome work here!

Love your app, and have written about it :)

**Comment by n0shake** [comment]
Thanks for the report; I'll take a stab at fixing this soon!

**Comment by n0shake** [comment]
This should be fixed with bf99807553e77b118305008a6b989e814b277260 and will be available as part of the next public release!
