### ISSUE TITLE
Please add UTC shift to appearance

### ISSUE THREAD

**Issue by mdeguzis** [n0shake/clocker#109]
I'd really love it if you could add the relative UTC shift to the appearance as an option. For example, "UTC-4". I love this app, just would like to see that so I know each region.

<img width="334" alt="image" src="https://user-images.githubusercontent.com/3931917/175973853-529ea25b-497e-47ca-913b-cbae3d3b1b7f.png">

**Comment by n0shake** [comment]
Thanks for the feedback @mdeguzis. Can you leverage custom labels to accomplish what you want to achieve (for eg: rename to **Amsterdam (UTC+1)**. We can definitely consider adding this if there's a genuine user need for this. Right now, there isn't. 

I'm going to keep this issue for a while and see how others feel about this :)

**Comment by n0shake** [comment]
I'm making the offset information available on hover; feedback welcome :)

<img width="401" alt="Screen Shot 2022-07-24 at 12 50 56 PM" src="https://user-images.githubusercontent.com/8280282/180657854-70e87a4b-3008-441b-b6b7-0b4d1ceb4d71.png">

**Comment by mdeguzis** [comment]
I updated it with `brew` but did not see the hover over yet.

**Comment by mdeguzis** [comment]
Works now:
```
==> Upgrading 1 outdated package:
clocker 22.06 -> 22.07
```

thank you!!!!
