### ISSUE TITLE
New v22.06 is not relasesed in github

### ISSUE THREAD

**Issue by fernandomora** [n0shake/clocker#110]
New version v22.06 is not available in github https://github.com/n0shake/clocker/releases
So brew formula cannot be upgraded https://github.com/Homebrew/homebrew-cask/blob/88ad8ce/Casks/clocker.rb

The only place I currently am able to find it is Apple Store

Is this deliberated, or just missing?

**Comment by n0shake** [comment]
It's now available as a GitHub release!
