### ISSUE TITLE
Use fixed-width digits

### ISSUE THREAD

**Issue by ryandesign** [n0shake/clocker#112]
Clocker is evidently using standard proportional-width digits such that the width varies depending on the time. This is especially apparent if you show the seconds.

If my menubar is especially full of regular menus and menu extras, I've seen it happen that a menu extra will appear and disappear from second to second depending on the time as more or less space becomes available. This is distracting.

Apple's clock doesn't have this problem.

Clocker should ask for fixed-width digits. ([`monospacedDigitSystemFontOfSize:weight:`](https://developer.apple.com/documentation/appkit/nsfont/1528205-monospaceddigitsystemfontofsize)?)

**Comment by n0shake** [comment]
@ryandesign - Clocker does use a monospaced font for rendering the time: 
https://github.com/n0shake/clocker/blob/642303d1385fc76c8723e4d18146d669973ee9b9/Clocker/Menu%20Bar/StatusItemView.swift#L13

The issue you're describing is most likely happening due to incorrect sizing logic calculation for the container view that renders the menubar item.

**Comment by ryandesign** [comment]
I see you closed this issue but I don't see any new commits in this repository since I opened this issue. How was the issue fixed?

**Comment by n0shake** [comment]
There's a seperate issue tracking this: https://github.com/n0shake/clocker/issues/102

**Comment by ryandesign** [comment]
#102 does not look like my issue. I'm not using multiple clocks, and I'm on Catalina, not Monterey.

**Comment by ryandesign** [comment]
This is the problem I'm reporting:

![out](https://user-images.githubusercontent.com/429209/197735391-c32af0a1-7782-42a5-afba-d242ce6e94ce.gif)

**Comment by ryandesign** [comment]
Could you reopen this issue, please?
