### ISSUE TITLE
Japan Standard Time shows up as "JDT" when it should be "JST"

### ISSUE THREAD

**Issue by beesyrupfactory** [n0shake/clocker#120]
Hello,

Japan time shows up as JDT when it should be JST (no daylight savings or summer time shifts in Japan).

Steps to reproduce:
1. Install and set up Clocker 23.01 (109)
2. Open the clock from the menubar
3. Click the + button
4. Add Asia/Tokyo then give it the label "Japan" save the entry
5. Mouse over the entry for "Japan"

Results:
We see JDT (UTC+9.0) -- The UTC time offset is correct, but the label should not be JDT. It should be JST.

![image](https://github.com/n0shake/clocker/assets/86087525/e064b899-598c-4c3c-8816-b4bedecddf04)

Thank you!

**Comment by n0shake** [comment]
Fixed via fa4887e.
