### ISSUE TITLE
Clocker complains about not being in /Applications incorrectly

### ISSUE THREAD

**Issue by mitchty** [n0shake/clocker#125]
Ola, so this check here:
https://github.com/n0shake/clocker/blob/master/Clocker/AppDelegate.swift#L208-L237

Appears to not truly be getting the base path for the app when the application is in /Appliations/some path with a space/

<img width="328" alt="Screen Shot 2023-09-06 at 4 31 16 PM" src="https://github.com/n0shake/clocker/assets/611923/68eb8f54-d570-47f9-8dbe-7555d8613454">

This should be a valid path for starting at login without having someone set that key noted in the source. Could this also not be a fatal condition for startup? I've never written any swift but if its an easy fix I can try to give it a go to fix it to work.

Cheers!

**Comment by n0shake** [comment]
> This should be a valid path for starting at login without having someone set that key noted in the source. 

I just put Clocker into `/Applications/Folder with Space` and didn't run into issues loading the app ¯\_(ツ)_/¯

> Could this also not be a fatal condition for startup?

The reason this was added as a fatal was because if the app isn't in /Applications, it affects the start at login functionality. Feel free to fork and remove the fatal :)
