### ISSUE TITLE
wishlist: show date for current timezone only, separate from time display

### ISSUE THREAD

**Issue by slippycheeze** [n0shake/Clocker#36]
My dream layout for multiple timezones (default: NYC) would be this:

[Fri Feb 23 20:35 SF 17:35 D 1:35+]

That is:  <date in NYC> <time in NYC> SF <SF time> D <Dublin time> <+ for "next day">

Using a "+" or "-" to indicate "next" or "previous" day is compact, which is much nicer on a small display.  (Alternative: something like http://www.iconarchive.com/show/windows-8-icons-by-icons8/Time-Date-To-icon.html would also work well.)

Showing only the local date is useful to me: I almost never care what the date is in the other location, and only very rarely if it is the next or previous day.  (Basically, only if it is Friday or Monday locally, and I want to know "will I get a response today, or is it already the weekend there")

I also don't need a label on the local time zone, since that is gonna be my default interpretation of that time, and the remaining ones are labelled.  Dividers would also be nice.

I can get most of that today by setting my timezone names to "⏐", "⏐SF", and "⏐D", but I couldn't get no label at all on NYC, since any whitespace-only content is treated as "use the default".

Bonus points: I'd really, really love to be able to use YYYY-MM-DD format for the date.  Note that this *is* the date format set in my "regional settings" in the control panel, for all four of the time "sizes", so simply respecting those would be sufficient.

**Comment by amit0rana** [comment]
my 2 cents

- I don't use Clocker for my 'local' date/time. I use 'Mini Calendar' for local date/calendar and Mac's default time for local time
- I find 'day' very useful and quick to read. I may get used to +/- but as of now I like to see day
- I can imagine if someone uses clocker for local datetime then not showing label is a good idea.

**Comment by abhishekbanthia** [comment]
@slippycheeze about the labels/divider. You can work around this in the current version. Just edit the label with a '|' or '' label to customize how you want your local timezone to appear.

**Comment by n0shake** [comment]
Hi @slippycheeze, thanks you for your feedback! I feel the new Compact Mode helps should address some issues you're seeing. 

> Showing only the local date is useful to me: I almost never care what the date is in the other location, and only very rarely if it is the next or previous day. (Basically, only if it is Friday or Monday locally, and I want to know "will I get a response today, or is it already the weekend there")

I dog-food Clocker a lot and prioritize features that suit my requirements (Sorry for being selfish). I interact with colleagues from a lot of different countries and there are some unique work-week challenges which makes knowing dates in other locations pretty useful for me. Some examples:

- I found out that for Middle Eastern countries; Friday is when the weekend starts and as a result I needed to avoid late meetings on Thursday.
- Wednesday is Work For Home for some offices I interact with while Tuesday is a No-Meetings-Day for some other offices.

> Bonus points: I'd really, really love to be able to use YYYY-MM-DD format for the date. Note that this is the date format set in my "regional settings" in the control panel, for all four of the time "sizes", so simply respecting those would be sufficient.

This is something I want to add as well and it's in my queue.

Thanks again and feel free to reopen if you have any more ideas.
