### ISSUE TITLE
'Home' Timezone - Feature request

### ISSUE THREAD

**Issue by amit0rana** [n0shake/Clocker#38]
Add a setting to indicate specific TZ is 'home' and display it automatically if Clocker finds that I am currently not in my home TZ.

Along same lines, settings to not show 'local' TZ.

For eg:
I have offices in NJ, Sydney and Bangalore. I do not want to see my local Time in Clocker (may be specific to me, for my local time I prefer Mac's clock). So when I am in Bangalore I like to see NJ, Sydney and when I travel to say Sydney, clocker should automatically start showing me NJ and Bangalore.
- Removed Sydney because that's my local TZ
- Added Bangalore because that was my home TZ.

**Comment by n0shake** [comment]
That's a great suggestion and sorry for getting back so late.

I've been thinking about this; while it's extremely useful, I haven't received any feedback from other users requesting something similar. I'll revisit this when there's more demand. Feel free to reopen if you'd like to add anything.
