### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by roko-p** [n0shake/Clocker#41]
At least in my case, Clocker uses a *lot* of CPU, and after some time always gets to above 90% at which point I kill it. (And I've kind of grown tired of restarting it)

Here's some info about my system:

```
  System Version:	macOS 10.13.6 (17G65)
  Kernel Version:	Darwin 17.7.0

  Model Identifier:	MacBookPro14,3
  Processor Name:	Intel Core i7
  Processor Speed:	2,8 GHz
  Number of Processors:	 1
  Total Number of Cores: 4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
```
Is this a known issue?

**Comment by abhishekbanthia** [comment]
Did you have the option "Show Next Meeting in Menu Bar" turned on? If so, does turning it off helps?

<img width="675" alt="screen shot 2018-08-13 at 21 00 43" src="https://user-images.githubusercontent.com/8280282/44067628-0ad58bc4-9f3c-11e8-8bf0-2e40b0fd3962.png">

**Comment by roko-p** [comment]
Yes I did, and yes, it seems it does!
A couple of days with that option turned off, all seems good ☺️ 
I'll keep it turned off until it possibly gets fixed in an update some day, thanks!!!

**Comment by LordNacho** [comment]
@abhishekbanthia I have all these turned off, but CPU usage is still 40%

**Comment by abhishekbanthia** [comment]
Hi @LordNacho, that's a lot. Can you help me with the following:

1. The number of timezones you have? 
2. The number of timezones you're displaying in your menubar 
2. Are you using the compact menubar mode?
3. If possible, can you attach a screenshot of your Appearance tab in Preferences.

Thanks

**Comment by LordNacho** [comment]
1. 7
2. 7
3. Yes
4. 
<img width="595" alt="screenshot 2019-01-15 at 21 43 08" src="https://user-images.githubusercontent.com/1208668/51211828-931e8c00-190e-11e9-98cc-e83cdfa75534.png">

**Comment by LordNacho** [comment]
Note I killed the app after this happened. Just put it back, but CPU is not back, it's more or less zero now.

**Comment by n0shake** [comment]
Haven't had reports of high CPU usage in a while. If it's still happening, please feel free to reopen this :)
