### ISSUE TITLE
1.6.01 issues

### ISSUE THREAD

**Issue by unthingable** [n0shake/Clocker#43]
![image](https://user-images.githubusercontent.com/925755/44314363-263daf00-a3cd-11e8-9d12-461b3e842fdf.png)

That is not the world I know. :)

After upgrading from 1.5...

1. The times are all local.
1. What happened to the compact layout? Would really like it back.
1. Clocker did not detect a time zone change, still thinks I'm in the previous one... but the new time zone appears to have been added to the bottom of the list. The new and the old timezones seem to have lost sunrise/sunset times.
1. All timezones flipped to 12-hour format (fixable by flipping each one to "Global").
1. Still no #31 :(

**Comment by unthingable** [comment]
5 - ... but the new time zone appears to have been added to the bottom of the list. The new and the old timezones seem to have lost sunrise/sunset times.

**Comment by abhishekbanthia** [comment]
This should be fixed in 1.6.02.

**Comment by unthingable** [comment]
Removed the point about the "pin" icon (was referring to 
![image](https://user-images.githubusercontent.com/925755/44896610-11301c80-acf9-11e8-8395-90d2618e6276.png)) after discovering what it does. That changed the list numbering :(

3 (former 4): After readding the time zones they were no longer affected by the local timezone change, so the issue is minor

5 (former 6): Not exactly. Example use case: you are on a call and trying to quickly find a time for a multi-zone meeting. Having the time slider "snap" to the hour will make it much easier to get a whole picture rather than repeatedly typing in different times. The date is not as important in this case.

**Comment by n0shake** [comment]
5. should be addressed by the new release. Closing!
