### ISSUE TITLE
"Anywhere on Earth" timezone

### ISSUE THREAD

**Issue by fspiga** [n0shake/Clocker#45]
https://www.timeanddate.com/time/zones/aoe

**Comment by neeklamy** [comment]
Interesting, I’d never heard of this.

> Anywhere on Earth (AoE) is a calendar designation which indicates that a period expires when the date passes everywhere on Earth. The last place on Earth where any date exists is on Howland and Baker islands…
>
> [World map of time zones, with the UTC-12 time zone highlighted.]
> – [Anywhere on Earth - Wikipedia](https://en.wikipedia.org/wiki/Anywhere_on_Earth)

It’d be nice to have UTC too.

**Comment by abhishekbanthia** [comment]
UTC is already present! You'll need to go to the timezone tab.

<img width="745" alt="screen shot 2018-09-10 at 8 02 27 am" src="https://user-images.githubusercontent.com/8280282/45299056-f6fff680-b4cf-11e8-9ab1-29c24ad69ad6.png">

**Comment by neeklamy** [comment]
Thanks! I just typed in `utc` (lowercase) and didn’t see it there at the top of the list:

![wheres-my-utc](https://user-images.githubusercontent.com/155358/45308051-84673900-b518-11e8-96d0-5ac89feffe26.png)

**Comment by n0shake** [comment]
Anywhere on Earth coming soon!

<img width="396" alt="Screen Shot 2019-04-07 at 2 38 07 PM" src="https://user-images.githubusercontent.com/8280282/55690177-dfdc9680-5942-11e9-8712-95bf603e4301.png">
