### ISSUE TITLE
Slider "snap" to hours option

### ISSUE THREAD

**Issue by unthingable** [n0shake/Clocker#46]
A reincarnation of #31 :)

Use case: you are on a call and trying to quickly find a time for a multi-zone meeting. Having the time slider "snap" to the hour is faster than either "hunting" for the hour with a continuous slider or repeatedly typing in different times, and will make it easier to see the whole picture quickly. The date is not as important in this case.

**Comment by n0shake** [comment]
Better late than never. The new [release](https://github.com/n0shake/Clocker/releases) supports snapping to 15, 30, 45, 60 minute intervals!

Let me know if you see any issues or have any feedback! :)
