### ISSUE TITLE
Clocker no more available in brew cask

### ISSUE THREAD

**Issue by carlosrberto** [n0shake/Clocker#56]
I got the following when trying to install using `brew cask`:

```sh
➜  ~ brew cask install clocker
Error: Cask 'clocker' is unavailable: No Cask with this name exists.
➜  ~ brew search clocker
No formula or cask found for "clocker".
Closed pull requests:
Delete clocker.rb (https://github.com/Homebrew/homebrew-cask/pull/54474)
Clocker (https://github.com/Homebrew/homebrew-cask/pull/37724)
Update clocker - uninstall launchctl (https://github.com/Homebrew/homebrew-cask/pull/37916)
```

**Comment by shlomi-nx** [comment]
I experience the same thing. How could clocker be installed not through the market place?

**Comment by NathanUrwin** [comment]
Hey @n0shake 👋 

Fantastic project you have here! Is there a reason you dropped brew cask support? And is there anyway we could add it back?

Thanks for your hard work on this project so far!

**Comment by n0shake** [comment]
Sorry for catching up late on this thread. The support isn't officially dropped, it's just not maintained. Very few users actually download the app using `brew cask`; so I decided to invest my time elsewhere. I'll try and see if this step can be automated.

**Comment by NathanUrwin** [comment]
Thanks for the quick response! :smile:

Oh I see that makes sense. Yes, please do! I would be happy to help as well, so please just let me know if I can do anything.

Going to reiterate the EDIT from my last comment here in case you missed it: Is there a reason you stopped making GitHub releases for App Store updates as well?

Thanks for your time!

**Comment by TheGamer007** [comment]
+1 would it be possible to get a Github zip release for the current version? I can't use the App Store to download the app since it is a work device and the latest release on Github (v1.5.1) is from 2017. Thank you!

**Comment by n0shake** [comment]
I'm sorry this isn't high-pri for me as very few users actually download the app from GitHub releases. Plus, there's app notarization to take care of (ugh). I'm happy to guide if someone wants to take a stab :)

**Comment by luanafaustini** [comment]
Hey @n0shake I saw Clocker at my collegues screen and went immediatly ask where could I find it to use as well.
Unfortunately I also can't download from Apple Store. Could you kindly share a .dmg?

**Comment by luanafaustini** [comment]
~ I imagine that is a huge work to update in each plataform, but I wanted so bad ~

Maybe someone knows another tool to point it out for me?

**Comment by luanafaustini** [comment]
[Clocker.zip](https://github.com/n0shake/Clocker/files/5608415/Clocker.zip)

My friend sent me the app. Sharing here for who has problems with app store. hope that's ok!

**Comment by n0shake** [comment]
@NathanUrwin  @luanafaustini Got some time over the weekend and I've added the latest release on GitHub:

https://github.com/n0shake/Clocker/releases/tag/20.10.03

**Comment by n0shake** [comment]
Clocker is now available in `brew cask`. [Link](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/clocker.rb) for the curious.

**Comment by carlosrberto** [comment]
Thanks!
