### ISSUE TITLE
Option to hide AM/PM

### ISSUE THREAD

**Issue by lukasolson** [n0shake/Clocker#57]
Just discovered Clocker today and love it! It would be nice if there were an option to hide AM/PM, even when not using 24-hour times. It's not often I don't know if it's AM or PM :)

Main reason I'm requesting is that the Date & Time preferences in MacOS have this option and I've been using it for awhile, but since I don't need the system time in the menu bar any more, I'd like to keep the AM/PM hidden.

**Comment by n0shake** [comment]
Better late than ever. This should be available now.

<img width="321" alt="Screen Shot 2021-01-30 at 06 39 34 PM" src="https://user-images.githubusercontent.com/8280282/106371487-9389f400-632a-11eb-91c6-a972278695db.png">
