### ISSUE TITLE
Local Timezone doesn't have sunrise/sunset time?

### ISSUE THREAD

**Issue by LordNacho** [n0shake/Clocker#58]
Why is the timezone you're most likely to care about not displaying it?

<img width="347" alt="screenshot 2019-01-28 at 20 10 26" src="https://user-images.githubusercontent.com/1208668/51863437-ea722280-2338-11e9-9339-21cee8f16f0a.png">

**Comment by n0shake** [comment]
Local timezones are timezones. To calculate sunrise and sunset times, Clocker requires a latitude/longitude which we can associate with a place but not a timezone.

A workaround would be to add your local city. Let me know if you have any questions.

**Comment by LordNacho** [comment]
Ah, good point, thanks!
