### ISSUE TITLE
Day of week display for Seoul is showing Monday when it should show Sunday

### ISSUE THREAD

**Issue by kevinflo** [n0shake/Clocker#59]
Currently it's showing Monday for Seoul when it should be displaying Sunday
![Screen Shot 2019-04-07 at 12 16 54 AM](https://user-images.githubusercontent.com/661291/55679083-ac5e2580-58ca-11e9-94a8-c64a7474fadf.png)

Interesting though that it shows correctly in mmm/dd format

![Screen Shot 2019-04-07 at 12 19 07 AM](https://user-images.githubusercontent.com/661291/55679091-e5969580-58ca-11e9-97b6-e1e552eeab9c.png)

**Comment by n0shake** [comment]
Hi @kevinflo, thanks for reporting this. I'm able to reproduce this quite easily. 

I'll take a look soon.

**Comment by n0shake** [comment]
The new App Store version landed. Please reopen the issue if you see it again.
