### ISSUE TITLE
Time disappeared from task bar after upgraded to 1.6.08

### ISSUE THREAD

**Issue by skys215** [n0shake/Clocker#60]
Hi,

I've upgrade to 1.6.08. And after upgrading, I've tried restarting the computer, but it never appears on the menu bar.
I'm using Sierra.

Any idea? Thank you

**Comment by n0shake** [comment]
Apologies for the issue. Can try resetting your preferences and see if that helps. Here’s how you do that:

1. Make sure Clocker is closed (force quit through Activity Monitor if necessary)
2. Open up the Terminal app and type in the command: `defaults delete com.abhishek.Clocker`
3. Hit the return key
4. Restart Clocker

You’ll need to add your places/timezones again.

**Comment by skys215** [comment]
Yeah, the problem is solved. Thanks
Do you need any logs for debugging?
