### ISSUE TITLE
The clocker crashes after selecting Menubar Mode to Standard

### ISSUE THREAD

**Issue by skys215** [n0shake/Clocker#61]
Hi,

I was trying every options in the clocker and when I choose `Standard` in the Menubar Mode on the `Menubar display options` of `Appearance` tab, the clocker crashes.

I'm wondering if this is related to the [previous issue](https://github.com/n0shake/Clocker/issues/60) which I posted recently.
Because I have noticed that `Compact` is selected in Menubar Mode. It shows different with previous version on the menubar(before I upgrade the clocker), the location and the time was showed in one line. I assume that `Standard` is what I was using.

Thanks.

**Comment by n0shake** [comment]
If I had to guess, the date calculations may have been going a little wonky for a particular location. Can you send me a screenshot of the timezones you've selected?

**Comment by skys215** [comment]
![image](https://user-images.githubusercontent.com/4977935/55738942-7d48d080-59fe-11e9-9933-1eeaee635192.png)
It's `深圳`, type`shenzhen` and the first result is it.

**Comment by n0shake** [comment]
Perfect; thanks. quick follow up questions:

1. What's your locale?
2. What's your user preferred language?

**Comment by skys215** [comment]
1. I'm in Brazil right now.
2. I'm using Chinese.

**Comment by n0shake** [comment]
I'm unable to reproduce this. Do you have any special date/formatting set in your System Pref?

<img width="780" alt="Screenshot 2019-04-08 at 21 10 18" src="https://user-images.githubusercontent.com/8280282/55772816-be62d400-5a42-11e9-8438-4f7e932b3142.png">

**Comment by skys215** [comment]
By the way, are there any way to get log of the clocker?
Maybe it'll be easier for you to debug the problem?

**Comment by n0shake** [comment]
I have a crash reporting service hooked up which should send up any relevant logs. but yeah you cang go to Console and search for Clocker and see if anything comes up.

**Comment by skys215** [comment]
After set to `Standard Mode` it crashes with:
![image](https://user-images.githubusercontent.com/4977935/55882209-7e9f0800-5b7a-11e9-93a5-8b67d06fcf0b.png)

After restarting clocker after the crash, has 3 logs:
1.
![image](https://user-images.githubusercontent.com/4977935/55882286-a3937b00-5b7a-11e9-90ec-9f9c29482d58.png)
2.
![image](https://user-images.githubusercontent.com/4977935/55882302-aee6a680-5b7a-11e9-9436-449a5adf8c9b.png)
3.
![image](https://user-images.githubusercontent.com/4977935/55882318-b4dc8780-5b7a-11e9-8f6e-d2a9551cb00e.png)

**Comment by n0shake** [comment]
Following up; do you have the option "Show Next Meeting title in the menubar" enabled?

**Comment by skys215** [comment]
I didn't see that option.

**Comment by n0shake** [comment]
@skys215 I've added extra logging which should help us debug crashes like this. Marking this closed for now but let me know if you still see issues.
