### ISSUE TITLE
"Display time in seconds" setting no longer seems to work

### ISSUE THREAD

**Issue by chlab** [n0shake/Clocker#66]
It seems that since the update to `1.6.10 (65)`, the setting "Display the time in seconds" no longer seems to work. I had it set to No but it's displaying the seconds anyway. I tried toggling it to Yes, then back to No but it shows the seconds anyway. I also tried restarting the app.

I am on Mojave 10.14.5.
Please let me know if I should supply any other information.

Thanks for the good work!

**Comment by LordNacho** [comment]
Same problem here, it shows seconds regardless of what is selected.

**Comment by incandescentman** [comment]
Temporary workaround: Toggle seconds from the overflow menu
<img alt="Screen Shot 2019-07-18 at 9 04 03 AM" width="721" src="https://user-images.githubusercontent.com/8280282/61473340-127f2d80-a93b-11e9-8c80-4ca4c4460a5b.png">

Source: https://github.com/n0shake/Clocker/issues/65
