### ISSUE TITLE
after update, 12/24 hour setting does not work

### ISSUE THREAD

**Issue by krc** [n0shake/Clocker#67]
It is stuck in 24 hour time no matter which way you flip the toggle. I actually want it in 24 hour time, but when I put the toggle to 24h, the time is cut off on the 4th displayed timezone, as if it runs under the next item in the menu bar. When I flip it to 12 hour, it stays in 24h format, but it is no longer cut off.

**Comment by n0shake** [comment]
As a temp workaround, can you override the timezone's date format by clicking the three dots:
<img width="658" alt="Screen Shot 2019-07-18 at 2 18 28 PM" src="https://user-images.githubusercontent.com/8280282/61492852-06a96080-a967-11e9-8dc7-7d6419b8521f.png">

**Comment by n0shake** [comment]
This should be fixed in the last version. Please re-open if you still see this popping up.
