### ISSUE TITLE
Localization 

### ISSUE THREAD

**Issue by KovalevArtem** [n0shake/Clocker#68]
I am saddened that the program is in English only.
I suggest to localize the program.
I am ready to assist in the translation into Russian.
(For example, you can use the service Crowdin or any other. Crowdin is free for Open source projects.)

**Comment by n0shake** [comment]
Thanks for the feedback @KovalevArtem! I'm slowly moving towards migrating all hard-coded strings in Clocker from Interface Builder to code. This will make localization a breeze. Keep an eye out!

**Comment by n0shake** [comment]
@KovalevArtem the project is up on Crowdin. If you'd like to help translate, here's the invite link: https://crwd.in/clocker
