### ISSUE TITLE
Labels lost in menubar when switching between dark mode and light mode

### ISSUE THREAD

**Issue by danielcompton** [n0shake/Clocker#70]
My Clocker menubar app normally looks like this:

<img width="150" alt="Screenshot of Clocker (30-08-19, 12-00-37 PM)" src="https://user-images.githubusercontent.com/811954/63984096-c8828d80-cb1d-11e9-9535-2aa933cd0ed3.png">

When switching between Dark and Light mode, I lose the labels on my timezones:

<img width="162" alt="Screenshot of Safari (30-08-19, 12-01-19 PM)" src="https://user-images.githubusercontent.com/811954/63984142-e223d500-cb1d-11e9-928f-4068af034e46.png">

After I click on the Clocker menubar and close it, the labels return:

<img width="128" alt="Screenshot of Safari (30-08-19, 12-01-51 PM)" src="https://user-images.githubusercontent.com/811954/63984159-f5cf3b80-cb1d-11e9-847b-ae56914cd857.png">

**Comment by n0shake** [comment]
Yikes, thanks for reporting

**Comment by n0shake** [comment]
Fixed via 7284ff54a4beeee702c31619dfa6cf77b88b18cc. I'll keep this open until this goes out.

**Comment by danielcompton** [comment]
Thanks!
