### ISSUE TITLE
Add "System/Current/Local" to Timezone list for travellers

### ISSUE THREAD

**Issue by seafre** [n0shake/Clocker#71]
Add "System/Current/Local" to Timezone list.

This is particularly useful for travellers where Clocker can be set the the current system time, driven by macOS system time changing timezone based on new geolocation.

This resolves the issue of having to manually change the Clocker "Favourite" timezone when using Clocker as a direct replacement for the standard macOS time in the menu bar.

Great project, thank you :+1:

**Comment by n0shake** [comment]
Clocker already supports this with "home row". If your system timezone changes, Clocker listens to it and auto-updates the home row. The home row is signified by a "pin" icon next to it (see attached screenshot). Detecting timezone changes is not as granular as detecting location changes but has several micro-benefits in that Clocker doesn't get access to your location data and is not computationally expensive on your battery. 

![Screen Shot 2019-09-15 at 1 34 29 AM](https://user-images.githubusercontent.com/8280282/65380639-4573d380-dc94-11e9-95a8-e61ba8646f40.png)

**Comment by seafre** [comment]
My request was referring to the macOS Menu Bar time from Clocker should be able to automatically reflect the current timezone, based upon the local system time (which the app is using for all other calculations anyway).

<img width="285" alt="image" src="https://user-images.githubusercontent.com/1815807/65761304-70d44380-e116-11e9-9042-3bf9a73bc860.png">

In addition, the feature you describe is not functioning as I have no geolocation icon against the timezone (and I cannot see anything related to this in the settings):

<img width="374" alt="image" src="https://user-images.githubusercontent.com/1815807/65761383-98c3a700-e116-11e9-936a-7fafc499518f.png">

**Comment by n0shake** [comment]
The "home" row is added when you do a fresh install the app. If you've deleted it, you need to either reset your preferences or do a fresh install.

**Comment by seafre** [comment]
OK so the issue to raise should be the following?

**Add "Home row" aka. Local Timezone as selection option in Timezones list**

**Comment by seafre** [comment]
In addition, the Home row (which has changed time in macOS menu bar but not the name) stays static based upon the original installation when sorting the list by time:

![image](https://user-images.githubusercontent.com/1815807/65785851-f22dd500-e11a-11e9-91b3-cb3de2539ddd.png)

**Comment by n0shake** [comment]
v1.6.17 fixes the issue where the name doesn't change upon the timezone switch. I'll look into the sorting issue for next release. Thanks for the feedback!
