### ISSUE TITLE
incorrect schedule in the reference schedule of brazil 2019

### ISSUE THREAD

**Issue by EdZava** [n0shake/Clocker#74]
In Brazil in 2019, summer time no longer exists.
I fixed the schedule on the Mac manually, but in the App continues to miscalculate the schedule of Barcelona and other countries.

Incorrect
![image](https://user-images.githubusercontent.com/1155199/67251846-d16d4c80-f446-11e9-9dcb-3166f561cb22.png)

Correct
![image](https://user-images.githubusercontent.com/1155199/67251863-e053ff00-f446-11e9-8a50-70f2511b2e94.png)

Sample
https://time.is/en/Barcelona

**Comment by EdZava** [comment]
@n0shake 
some information ?
How does the app calculate the time difference of different time zones?

**Comment by n0shake** [comment]
Looks like a Daylights Saving time miscalculation. A quick workaround would be to add the `Central European Summer Time` timezone. I'll take a look soon.

The time difference between local time and a timezone's time is calculated [here](https://github.com/n0shake/Clocker/blob/0c2ed72decce4e4100d235bb7d0d98827940d9c2/Clocker/Panel/Data%20Layer/TimezoneDataOperations.swift#L210).

**Comment by EdZava** [comment]
@n0shake Try adding the "_Central European Summer Time_" time zone but you can't find it.

If it is a mistake for summer time. This is because in Brazil in 2019 summer time ceased to exist. Many systems are going through similar problems.

Look at the code in the section that you comment, but my knowledge of swift are very basic to help where the problem could be.

But it seems to me that it is because the api of the apple system that the schedule is not correct is going through the schedule.

**Note:** In the OS I have had to deactivate the automatic time adjustment, so that I can indicate to the system what the correct time is.

![image](https://user-images.githubusercontent.com/1155199/68671448-18260200-052e-11ea-8ef3-ef4e20afbcbd.png)

![image](https://user-images.githubusercontent.com/1155199/68671459-1c521f80-052e-11ea-9c3c-f46c5eff892f.png)

**Comment by EdZava** [comment]
do you plan to fix?
This error generates many problems for not knowing the correct schedule.

Please if you can check it. 🙏🏻🙏🏻🙏🏻

**Comment by EdZava** [comment]
Updated macOS for Catalina and now everything works correctly because the OS already takes into account the Brazilian time change.
