### ISSUE TITLE
Add EPOCH Time below the time and provide copy option

### ISSUE THREAD

**Issue by rayabhi24** [n0shake/Clocker#75]
Providing EPOCH time and copy option to that would be best and useful thing for programmer.
As well as if epoch converter is provided in display pan with default UTC and with first favourite time zone is great help at time of code development/debugging.

**Comment by n0shake** [comment]
Support for both features should be available in the latest release (v21.07.01). This release will be rolled out slowly over the course of the next week. Check out this thread for demos: https://twitter.com/clocker_support/status/1411116386332598277
