### ISSUE TITLE
Add missing release files.

### ISSUE THREAD

**Issue by Trevor-** [n0shake/Clocker#76]
The release files are missing, please can you add them.
Thanks.

**Comment by n0shake** [comment]
Which release files?

**Comment by Trevor-** [comment]
For example, https://github.com/n0shake/Clocker/blob/master/Clocker/Releases/appcast.xml line 13 refers to https://github.com/abhishekbanthia/Clocker/releases/download/v1.5.1/Clocker.zip
This was a release version that could be unzipped and placed in the applications folder.
If you could put the latest version of Clocker in there it would be very helpful.
I don't have access to the app store and am having trouble signing and compiling the source code.

BTW, great extension.
