### ISSUE TITLE
Cant find Tel Aviv / Israel time zone

### ISSUE THREAD

**Issue by razbensimon** [n0shake/Clocker#77]
Cant find any Tel Aviv / Israel's time zone

![image](https://user-images.githubusercontent.com/5955905/90115462-a9d3d180-dd43-11ea-9810-d2943c35d9e3.png)

**Comment by n0shake** [comment]
This should be fixed! Can you update to the latest version and verify? Marking this as resolved but feel free to re-open if this isn't fixed.

<img width="745" alt="Screen Shot 2020-11-29 at 12 00 21 PM" src="https://user-images.githubusercontent.com/8280282/100549774-9c7f1c00-323a-11eb-87aa-e60497a30975.png">
<img width="745" alt="Screen Shot 2020-11-29 at 12 00 28 PM" src="https://user-images.githubusercontent.com/8280282/100549775-9db04900-323a-11eb-863a-d8b75746b03d.png">
