### ISSUE TITLE
White color in macOS Big Sur

### ISSUE THREAD

**Issue by abdonrd** [n0shake/Clocker#78]
Should be black as others:

<img width="313" alt="Screenshot 2020-11-13 at 14 54 33" src="https://user-images.githubusercontent.com/1007051/99079398-2e8eef80-25c0-11eb-95fe-82a3c2563cfc.png">

**Comment by n0shake** [comment]
I'll be pushing the Big Sur update pretty soon which should fix this! Hang tight.

**Comment by n0shake** [comment]
Fixed in v20.10.03!
