### ISSUE TITLE
Failed to start the app

### ISSUE THREAD

**Issue by gabiudrescu** [n0shake/Clocker#79]
# Steps to reproduce: 

1. search the application name on Google
2. reach Apple Store web page
3. click install
4. open the native app 
5. install Clocker
6.  open Launchpad
7.  search for Clocker
8. click the icon
![image](https://user-images.githubusercontent.com/5156054/100370847-95c09100-300f-11eb-8304-95d9d48f6cb6.png)

# What happens:
you receive the error below 
![image](https://user-images.githubusercontent.com/5156054/100370910-aec94200-300f-11eb-8d50-29ea31493917.png)

am I doing something wrong?

**Comment by n0shake** [comment]
Unable to repro it on my end on BigSur. Are you able to open it by navigating to Applications and double-tapping the icon?
