### ISSUE TITLE
Timezone ahead/behind not displayed correctly [GER]

### ISSUE THREAD

**Issue by philippMB** [n0shake/Clocker#81]
It is not displayed correctly if a timezone is ahead or behind in German. Because this does not seem to be part of the Localization strings, I open this issue here. 
![Bildschirmfoto 2021-01-18 um 17 45 38](https://user-images.githubusercontent.com/24268096/104942677-0bfcc680-59b5-11eb-9cbc-3108ff24f5aa.png)
It always says "Vor X Stunden", which means it was this time X hours earlier. At the same time it could mean, you have to go X hours ahead. Both is not ideal. 
Suggestion: Change it to "X Stunden vor" for ahead and "X Stunden zurück" for behind.

**Comment by n0shake** [comment]
@philippMB can you tell me which Clocker version you're on?

**Comment by philippMB** [comment]
@n0shake my version is 20.10.03. Just downloaded from the AppStore

**Comment by n0shake** [comment]
Should be resolved through f343c9eb55b6ba5b98a41c2b6d4012c0db14b256. I'll keep the issue open until the fix is pushed to the App Store.
