### ISSUE TITLE
-- 12 Hour w/o AM/PM --  time format incorrect

### ISSUE THREAD

**Issue by thezoggy** [n0shake/Clocker#85]
Clocker version: 21.02.02 (91)

Few formats do not align with reality, the bottom -- 12 Hour w/o AM/PM -- times formats are both incorrect

time format: `hh:mm (07:08)` results in hh:mm:ss
time format: `hh:mm:ss (07:08:09)` results in h:mm a

**Comment by n0shake** [comment]
@thezoggy are you setting the timezone formats at the individual timezone level or in the Preferences?

**Comment by thezoggy** [comment]
Preferences

**Comment by n0shake** [comment]
@thezoggy what's the format selection at the individual timezone level?

<img width="688" alt="Screen Shot 2021-02-02 at 8 28 44 PM" src="https://user-images.githubusercontent.com/8280282/106689347-76a52900-6595-11eb-9aba-afa41cffa1d3.png">

**Comment by thezoggy** [comment]
never knew you could customize at the timezone specific.  this should show you everything you want:
<img width="712" alt="Screen Shot 2021-02-02 at 8 41 19 PM" src="https://user-images.githubusercontent.com/500882/106690229-0f887400-6597-11eb-800d-c9a3364b10ea.png">

**Comment by n0shake** [comment]
This should be fixed through 64ce22e4456e4acc0cae40715a25bd1e297085c5.
