### ISSUE TITLE
Quick Add Locations - unable to add utc

### ISSUE THREAD

**Issue by thezoggy** [n0shake/Clocker#86]
Clocker version: 21.02.02 (91)

On first run, the quick add locations does not allow you to add the same locations that the add allows once you run the app.

* Not clear that the app adds your current timezone by default (as I added my local city to find it ends up being a duplicate)
* Unable to add UTC/GMT during setup

**Comment by n0shake** [comment]
Great feedback!! I'll address this soon :)

**Comment by n0shake** [comment]
> Not clear that the app adds your current timezone by default (as I added my local city to find it ends up being a duplicate)

Addressed through 12d7684ec925f4269e3c7515e2af1f176092b747.

**Comment by n0shake** [comment]
> Unable to add UTC/GMT during setup

Fixed through 54a55c15d48193840a6bf9ada880adb512fce65c.
