### ISSUE TITLE
Preferences > Appearance > Misc > Menubar Options - not initialize correctly

### ISSUE THREAD

**Issue by thezoggy** [n0shake/Clocker#87]
Clocker version: 21.02.02 (91)

Preferences > Appearance > Misc > Menubar Options

The include date/day/etc default to Yes but actually do not.
You have to click on No then Yes for the option to make the menubar update.

**Comment by n0shake** [comment]
Fixed through 2947588f29b6bd93e56b632489147111c44a1c59.
