### ISSUE TITLE
Sunrise/Sunset time format does not match selected time format in Preferences > Appearance

### ISSUE THREAD

**Issue by AutonomousEngineer** [n0shake/Clocker#88]
The time format used for the Sunrise/Sunset of a location does not match the selected format in Preferences > Appearance.

![image](https://user-images.githubusercontent.com/3311455/106815039-4adf7d00-6641-11eb-946d-032d0deded5c.png)

Clocker 21.02.03 (92)

**Comment by n0shake** [comment]
Fixed through my last commit. Attaching screenshot for ref:

<img width="396" alt="Screen Shot 2021-02-06 at 10 38 00 PM" src="https://user-images.githubusercontent.com/8280282/107136830-2ba85000-68cc-11eb-995c-bcedd5bbf835.png">
