### ISSUE TITLE
Date/time format doesn't match system

### ISSUE THREAD

**Issue by Drarok** [n0shake/Clocker#90]
Clocker on the left, system clock on the right, note the "15" is in a different place:
![Screenshot 2021-02-15 at 09 07 39](https://user-images.githubusercontent.com/55830/107926345-7fbad080-6f6d-11eb-852a-29a81f7418e4.png)

**Comment by n0shake** [comment]
@Drarok Do you happen how to retrieve the date format set in the system menubar? Looking at docs and at this [Apple Support page](https://support.apple.com/guide/mac-help/change-dates-times-display-mac-mh27073/mac#:~:text=Tip%3A%20If%20you%20just%20want,the%20Menu%20Bar%20Clock%20pane) isn't much help :/

**Comment by n0shake** [comment]
Closing as I'm not aware of any way Clocker can derive the time format set in the system clock.

**Comment by Drarok** [comment]
I think it's just the locale default? This shows my (`en_GB`) locale correctly. Not sure why the US one has a comma, though?!

```swift
import Foundation

let dateFormatter = DateFormatter()
dateFormatter.dateStyle = .medium
dateFormatter.timeStyle = .none

let date = Date(timeIntervalSinceReferenceDate: 118800)
let localeIdentifiers: [String] = ["en_US", "en_GB", "fr_FR", "ja_JP"]

localeIdentifiers.forEach {
	let locale = Locale(identifier: $0)
	dateFormatter.locale = locale
	dateFormatter.setLocalizedDateFormatFromTemplate("EEEMMMd")
	print($0, dateFormatter.string(from: date))
}

/*
$ swift example.swift
en_US Tue, Jan 2
en_GB Tue 2 Jan
fr_FR mar. 2 janv.
ja_JP 1月2日(火)
*/
```

**Comment by n0shake** [comment]
You can override the timezone format for the system menubar using Preferences. I don't see that's respected if we derive the time using locale and time-style.

<img width="780" alt="Screen Shot 2021-02-26 at 3 33 24 PM" src="https://user-images.githubusercontent.com/8280282/109357581-0f069480-7848-11eb-8b91-d64cc0705285.png">
