### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by weiweihuanghuang** [n0shake/Clocker#91]
I'd like to change the font in the app but don't have much experience building Swift apps, whats the procedure for Clocker?

**Comment by n0shake** [comment]
- Download the latest Xcode from developer.apple.com
- Fork/clone/download this repo
- You're most likely will run into certificate issues, so I'd suggest turning them off. Here's a [SO link](https://stackoverflow.com/questions/31039513/how-can-i-skip-code-signing-for-development-builds-in-xcode) that explains how you can achieve that.
- Profit?

Let me know if you run into any issues!
