### ISSUE TITLE
Odd behavior with latest v21.07.01

### ISSUE THREAD

**Issue by ricardoalcocer** [n0shake/Clocker#97]
For some very odd reason I can't understand, clicking on Clocker on the menu bar opens Zoom on my upcoming meeting.

Does this make any sense to you?

**Comment by ricardoalcocer** [comment]
Downgraded to v20.10.04 and works fine.

Let me know if I can assist on tracking this down.

**Comment by n0shake** [comment]
Thanks for reporting! I just received another report regarding this, and have paused the rollout of the latest version.

Investigating!

**Comment by n0shake** [comment]
This should be fixed via c48ef18e99df0174fa970818677f87b4eb2eb5cf. I'll be posting a new release soon!

**Comment by n0shake** [comment]
The new update was just approved by Apple and will be rolled out in a phased release over the next week. I've also added it under GitHub Releases.

**Comment by ricardoalcocer** [comment]
Thank you, @n0shake.  It's fixed now! 🎉
