### ISSUE TITLE
[CRITICAL] Settings button is gone

### ISSUE THREAD

**Issue by AlsoScratch** [n0shake/Clocker#99]
This is an extremely serious issue that I am facing where I have been unable to find the settings button since the latest update. If the button is still present, then it has probably gone past the bottom of my screen.

**Comment by n0shake** [comment]
Few questions:

- Can you send me a screenshot?
- Are you on 11" / 13" MacBook by any chance?

In the meanwhile, you can use keyboard shortcuts to open Preferences (Command + ,) or quitting (CMD + Q).

**Comment by AlsoScratch** [comment]
Mine is a 15 inch.

**Comment by AlsoScratch** [comment]
<img width="1440" alt="Untitled" src="https://user-images.githubusercontent.com/48752273/126685804-2357d091-0656-42af-a0b6-d2c64a079697.png">

**Comment by n0shake** [comment]
> Also, the command doesn't work for me.

@AlsoScratch Which one are you trying?

**Comment by AlsoScratch** [comment]
CMD + comma

**Comment by AlsoScratch** [comment]
Oh wait, it worked now.

**Comment by n0shake** [comment]
Fixed with b26d9bd6c52fb3dcffab7fe02cd67f78f212a6a5.
